(defun grade (percent)
  (cond ((>= percent 90) "A+")
        ((>= percent 85) "A")
        ((>= percent 80) "A-")
        ((>= percent 77) "B+")
        ((>= percent 73) "B")
        ((>= percent 70) "B-")
        ((>= percent 0) "F")
        ))
