(defun get-sports (array1 array2 x)
  (let ((array3 (make-array 0 :adjustable t :fill-pointer 0)))
    (dotimes (index (length array1) array3)
      (if (and (typep (aref array2 index) 'string)
               (equal (aref array2 index) (values x)))
          (vector-push-extend (aref array1 index) array3))
      )
    )
  )

(defun list-even (n)
  (let ((x (list 0))
        )
    (dotimes (index (+ n 1) x)
      (if (= 0 (mod index 2))
          (progn
            (setf x (cons index x)))))
    (setf x (reverse x))
    (setf x (rest x))
    ))
